[package]
name = "fertree"
version = "0.1.0"
authors = ["JT <mccronejt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
pest = "2.1.3"
pest_derive = "2.1.0"
pest_consume = "1.0.6"